services:
  frontend:
    build: ./ratkingcaffeine
    ports:
      - "4201:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"