services:
  frontend:
    build: ./ratkingcaffeine
    ports:
      - "4201:4200"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"